name: DartRedstoneBenchmark
description: A benchmark of Redstone.dart, a server-side microframework for Dart
environment:
  sdk: ">=1.3.0 <2.0.0"
dependencies:
  args: 0.10.0+2
  crypto: 0.9.0
  mongo_dart: 0.1.42
  mustache: 0.1.8
  postgresql: 0.2.13
  redstone: 0.5.9
  redstone_mapper: 0.1.3
  redstone_mapper_mongo: 0.1.1+1
  redstone_mapper_pg: 0.1.0
  yaml: 0.9.0